### ISSUE TITLE
Consider renaming dd()

### ISSUE THREAD

**Issue by micheleangioni** [zachleigh/yarak#22]
Hi,
since dd() is a very popular Laravel function, many developers (such as me) have defined their own dd() function in Phalcon.
In Unit Tests the Yarak helpers file is called at the very beginning, Yarak's dd() function is always defined before the custom application's dd().

Since I suppose Yarak's dd() is used only for Yarak's development, could you just rename it?

**Comment by sergeyklay** [comment]
Also see https://github.com/phalcongelist/dd :)

**Comment by zachleigh** [comment]
Required the dd package @sergeyklay mentioned as a dev dependency. Should solve the problem?
v1.1.2

**Comment by micheleangioni** [comment]
I confirm it seems to have solved the problem!
