### ISSUE TITLE
Specify how to manually run tests

### ISSUE THREAD

**Issue by micheleangioni** [zachleigh/yarak#24]
Hi,
please specify in the readme how to manually run tests, for people who want to contribute:

1. Run `composer install`
2. Specify a correct user/password in the `codeception.yml` file and `/app/config/config.php` files
3. Run `php vendor/codeception/codeception/codecept run`

Thanks.

**Comment by zachleigh** [comment]
Added basic developer documentation in the readme.

**Comment by micheleangioni** [comment]
:+1:
